logging:
  file:
    path: log
  level:
    org:
      springframework:
        boot:
          autoconfigure: debug
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    password: ''
    url: jdbc:h2:./database;
    username: sa